name: Build Docker Images
description: Buuid and upload docker images
inputs:
  registry-alias:
    default: ${{ github.repository_owner }}
    required: false
    description: repository alias
  repository:
    default: ${{ github.event.repository.name }}
    required: false
    description: repository name
  extra-tags:
    required: false
    description: additional tags for image
  aws-region:
    default: "us-east-1"
    required: false
    description: aws region
  role-duration-seconds:
    default: "900"
    required: false
    description: aws role duration
  role-arn:
    default: ""
    required: false
    description: aws role arn to access ecr
  role-session-name:
    default: ""
    required: false
    description: aws role name to access resources
  role-skip-session-tagging:
    default: "false"
    required: false
    description: skip role session tagging
  docker-registry:
    default: ""
    required: false
    description: docker registry

runs:
  using: composite
  steps:
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: true
    
    - name: tag images
      run: |
        echo 'Hi there!'
        docker tag ${{ inputs.repository }}/${{ inputs.registry-alias }}:${GITHUB_SHA::6} ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repository }}/${{ inputs.registry-alias }}:${GITHUB_SHA::6}
        docker images
      shell: bash

    - name: create repo if missing
      shell: bash
      run: |
        aws sts get-caller-id
        aws ecr describe-repositories --query 'repositories[*].repositoryUri' | jq -r '.[]'
    
